{-------------------------------------------------------------------------------
   Copyright 2012-2026 Ethea S.r.l.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------}

/// <summary>Accounting engine of the application: builds the double-entry journal
/// entries generated by enrollment approval and payment collection, numbers
/// movements and VAT protocols, and performs the year-end closing and reopening
/// of the balance sheet.</summary>
unit SCM.Accounting;

interface

uses
  DB
  , KItto.Store
  , Kitto.Metadata.Models
  , Kitto.Metadata.DataView
  , EF.Tree
  , EF.DB;

const
  //ENTRY TYPE
  SIMPLE_ENTRY = 'AS';
  COMPLEX_ENTRY = 'AC';
  CUSTOMER_INVOICE = 'FC';
  SUPPLIER_INVOICE = 'FF';
  CUSTOMER_CREDIT_NOTE = 'NC';
  SUPPLIER_CREDIT_NOTE = 'NF';
  OPENING_ENTRIES = 'MA';
  CLOSING_ENTRIES = 'MC';

  //SIGN
  DEBIT_SIGN = 'D';
  CREDIT_SIGN = 'A';

  //REASON TYPE
  GENERAL_LEDGER = 'GEN';
  SALES_VAT = 'CLI';
  PURCHASES_VAT = 'FOR';
  COLLECTION = 'INC';
  PAYMENT = 'PAG';

  //LEGAL FORM
  SOLE_PROPRIETORSHIP = 'DI';
  PRIVATE_INDIVIDUAL = 'PRI';
  GENERAL_PARTNERSHIP = 'SNC';
  JOINT_STOCK_COMPANY = 'SPA';
  LIMITED_LIABILITY_COMPANY = 'SRL';

  //automatic reasons
  PAYMENT_COLLECTION = 'INCPAG';
  SUBSCRIPTION = 'ISCR';
  BALANCE_SHEET_OPENING = 'APEBIL';
  BALANCE_SHEET_CLOSING = 'CHIUBIL';
  YEAR_PROFIT = 'UTILESERC';
  YEAR_LOSS = 'PERDESERC';
  PREV_YEAR_PROFIT = 'UTILESERCPREC';
  PREV_YEAR_LOSS = 'PERDESERCPREC';

  //FINANCIAL YEAR
  YEAR_CLOSED = 'C';
  YEAR_OPEN = 'A';

function NewEntryNumber(AFinancialYearId :  string) : integer;
procedure UpdateVatProtocol(AEntryId: string; AVatRegisterId : string; ADate : TDateTime);

function IsVatEntry(AEntryType : string): boolean;
function IsCustomerVatEntry(AEntryType : string): boolean;
function IsSupplierVatEntry(AEntryType : string): boolean;

//customer insertion
function InsertOrUpdateCustomer(const APersonId : string): string;

//insert the collection entry for the subscription instalment
procedure InsertCollectionEntryFromPayments(const ARecord: TKRecord);

//insert the subscription entry
procedure InsertSubscriptionEntry(const ARecord: TKRecord);

//returns the automatic reason
function GetReason(const AAutomaticReasonId : string) : string;

//returns the automatic reason description
function GetReasonDescription(const AAutomaticReasonId : string) : string;

//returns the posting type of the reason
function GetReasonPostingType(const AReasonId : string) : string;

//Returns the financial year open at the given date
function GetFinancialYearFromDate(const ADate : TDateTime): string;

//returns the query for the automatic accounts
function GetSQLAutomaticAccounts: string;

// returns the query that reads the reason data
function GetSQLReasonData: string;

//returns the insert query for the entries
function GetSQLInsertEntry: string;

//returns the insert query for the entry lines
function GetSQLInsertLine: string;

//returns the insert query for the VAT detail
function GetSQLInsertVatDetail: string;

//returns the insert query for the withholding taxes
function GetSQLInsertWithholdingDetail: string;

// returns the query that reads the subscription data
function GetSQLSubscriptionData: string;

//returns the query for the counterpart balance
function GetSQLCounterpartBalance: string;

//Closing and opening entries of the balance sheet
procedure CloseAndReopenBalanceSheet(const ServerStore: TKViewTableStore);

//Insert the accounting entry that closes the financial year
procedure InsertClosingEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AClosingYearId, AClosingAutoReasonId, AClosingAutoReasonDesc : string; AFinancialYearEnd : TDateTime;
  AClosingReasonDataQuery, AClosingAutoAccountsQuery, ACounterpartBalanceQuery: TEFDBQuery;
  AAccountId, ADescription, ASign, ASection : string; ABalance : Currency);

//insert the accounting entry that opens the financial year
procedure InsertOpeningEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AOpeningYearId, AOpeningAutoReasonId, AOpeningAutoReasonDesc : string; AFinancialYearStart : TDateTime;
  AOpeningReasonDataQuery, AOpeningAutoAccountsQuery, ACounterpartBalanceQuery: TEFDBQuery;
  AAccountId, ADescription, ASign : string; ABalance : Currency);

//insert the entry for the profit or loss of the year
procedure InsertProfitOrLossEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AFinancialYearId, AAutoReasonId, AAutoReasonDesc : string; ADate : TDateTime;
  AReasonDataQuery, AAutoAccountsQuery: TEFDBQuery;
  LProfitOrLoss : Currency; ANewFinancialYear : boolean);

//Closes the financial year
procedure CloseFinancialYear(AFinancialYearId : string);


implementation

uses
  SCM.Utils
  ,RegularExpressions
  ,EF.Localization
  ,Kitto.Config
  ,Kitto.Auth.DB
  ,Kitto.Rules
  ,System.SysUtils
  ,EF.StrUtils
  ,System.Variants
  ,EF.VariantUtils
  ,DateUtils
  ,SCM.DbUtils, Kitto.DbUtils;

function NewEntryNumber(AFinancialYearId :  string) : integer;
begin
  //read the entry number
  Result := EFVarToInt(TKConfig.Database.GetSingletonValue('SELECT NRMOV FROM ESERCIZICONTABILI WHERE ID = ''' + AFinancialYearId + ''''))+1;
  //write the new entry number to the database
  TKConfig.Database.ExecuteImmediate('UPDATE ESERCIZICONTABILI SET NRMOV = '+IntToStr(Result)+' WHERE ID = ''' + AFinancialYearId + '''' );
end;

procedure UpdateVatProtocol(AEntryId: string; AVatRegisterId : string; ADate : TDateTime);
var
  LProtIVA : integer;
  LCurrentVatYear : boolean;
begin
  LCurrentVatYear := YearOf(date) = YearOf(ADate);

  if LCurrentVatYear then
  begin
    //read the VAT protocol number
    LProtIVA := EFVarToInt(TKConfig.Database.GetSingletonValue('SELECT NR_PROT FROM REGISTRI_IVA WHERE ID = ''' + AVatRegisterId + ''''))+1;
    //write the new VAT protocol number to the database
    TKConfig.Database.ExecuteImmediate('UPDATE REGISTRI_IVA SET NR_PROT = '+IntToStr(LProtIVA)+', DATA_ULT_PROT = ''' + DateToCompactStr(ADate) + ''' WHERE ID = ''' + AVatRegisterId + '''' );

  end
  else
  begin
    //read the VAT protocol number
    LProtIVA := EFVarToInt(TKConfig.Database.GetSingletonValue('SELECT NR_PROT_PREC FROM REGISTRI_IVA WHERE ID = ''' + AVatRegisterId + ''''))+1;
    //write the new VAT protocol number to the database
    TKConfig.Database.ExecuteImmediate('UPDATE REGISTRI_IVA SET NR_PROT_PREC = '+IntToStr(LProtIVA)+', DATA_ULT_PROT_PREC = ''' + DateToCompactStr(ADate) + ''' WHERE ID = ''' + AVatRegisterId + '''' );
  end;

  TKConfig.Database.ExecuteImmediate('UPDATE MOVIMENTI_CONTABILI SET NR_IVA = '+IntToStr(LProtIVA)+' WHERE ID = ''' + AEntryId + '''' );
end;

function IsVatEntry(AEntryType : string): boolean;
begin
  Result := (AEntryType = CUSTOMER_INVOICE) or
            (AEntryType = SUPPLIER_INVOICE ) or
            (AEntryType = CUSTOMER_CREDIT_NOTE ) or
            (AEntryType = SUPPLIER_CREDIT_NOTE);
end;

function IsCustomerVatEntry(AEntryType : string): boolean;
begin
  Result := (AEntryType = CUSTOMER_INVOICE) or
            (AEntryType = SUPPLIER_INVOICE );
end;

function IsSupplierVatEntry(AEntryType : string): boolean;
begin
  Result := (AEntryType = CUSTOMER_CREDIT_NOTE ) or
            (AEntryType = SUPPLIER_CREDIT_NOTE);
end;

function InsertOrUpdateCustomer(const APersonId : string): string;
var
  LQuery: TEFDBQuery;
  LQueryText: string;
  LCommandText: string;
  LCommand: TEFDBCommand;
  LCustomerId : string;
begin
  LQuery := TKConfig.Database.CreateDBQuery;
  LCommand := TKConfig.Database.CreateDBCommand;
  Try
    //Read the data from the registry

    LQueryText := 'SELECT CODFISC, COGNOME, NOME, TELEFONO, CELLULARE, EMAIL, INDIRIZZO, CAP, '+
                    'PROVINCIAID, COMUNEID, DATANASC, LUOGONASCID, PROVNASCID, SESSO, NAZIONALITAID, IBAN '+
                    'FROM NOMINATIVI WHERE ID = :ID';
    LQuery.CommandText := LQueryText;
    LQuery.Params.ParamByName('ID').AsString := APersonId;
    LQuery.Open;
    try
      if not LQuery.DataSet.IsEmpty then
      begin
        LCustomerId := EFVarToStr(TKConfig.Database.GetSingletonValue('SELECT ID FROM CLIENTI WHERE CODFISCALE = '+QuotedStr(LQuery.DataSet.FieldByName('CODFISC').AsString)));

        if LCustomerId <> '' then
        begin
          LCommandText :=  'UPDATE CLIENTI '+
                           'SET DX = :DX '+
                           '   ,COGNOME = :COGNOME '+
                           '   ,NOME = :NOME '+
                           '   ,CODFISCALE = :CODFISCALE '+
                           '   ,INDIRIZZO = :INDIRIZZO '+
                           '   ,CAP = :CAP '+
                           '   ,PROVINCIAID = :PROVINCIAID '+
                           '   ,IBAN = :IBAN '+
                           '   ,EMAIL = :EMAIL '+
                           '   ,INDIRIZZO_AMM = :INDIRIZZO_AMM '+
                           '   ,CAP_AMM = :CAP_AMM '+
                           '   ,COMUNE_AMMID = :COMUNE_AMMID '+
                           '   ,PROVINCIA_AMMID = :PROVINCIA_AMMID '+
                           '   ,COMUNEID = :COMUNEID '+
                           '   ,FORMA_GIURIID = :FORMA_GIURIID '+
                           '   ,FLAG_INDI_AMM = :FLAG_INDI_AMM '+
                           '   ,TELEFONO = :TELEFONO '+
                           '   ,CELLULARE = :CELLULARE '+
                           'WHERE ID = :ID ';
        end
        else
        begin
          LCustomerId := CalcNewProgress('TISCliente', 10);
          LCommandText := 'INSERT INTO CLIENTI '+
                          '   (ID '+
                          '   ,DX '+
                          '   ,COGNOME '+
                          '   ,NOME '+
                          '   ,CODFISCALE '+
                          '   ,INDIRIZZO '+
                          '   ,CAP '+
                          '   ,PROVINCIAID '+
                          '   ,IBAN '+
                          '   ,EMAIL '+
                          '   ,INDIRIZZO_AMM '+
                          '   ,CAP_AMM '+
                          '   ,COMUNE_AMMID '+
                          '   ,PROVINCIA_AMMID '+
                          '   ,COMUNEID '+
                          '   ,FORMA_GIURIID '+
                          '   ,FLAG_INDI_AMM '+
                          '   ,TELEFONO '+
                          '   ,CELLULARE) '+
                          'VALUES '+
                          '  (:ID '+
                          '   ,:DX '+
                          '   ,:COGNOME '+
                          '   ,:NOME '+
                          '   ,:CODFISCALE '+
                          '   ,:INDIRIZZO '+
                          '   ,:CAP '+
                          '   ,:PROVINCIAID '+
                          '   ,:IBAN '+
                          '   ,:EMAIL '+
                          '   ,:INDIRIZZO_AMM '+
                          '   ,:CAP_AMM '+
                          '   ,:COMUNE_AMMID '+
                          '   ,:PROVINCIA_AMMID '+
                          '   ,:COMUNEID '+
                          '   ,:FORMA_GIURIID '+
                          '   ,:FLAG_INDI_AMM '+
                          '   ,:TELEFONO '+
                          '   ,:CELLULARE) ';
        end;
        LCommand.CommandText := LCommandText;

        UpdateParamValue(LCommand.Params,'ID', LCustomerId);
        UpdateParamValue(LCommand.Params,'DX', LQuery.DataSet.FieldByName('COGNOME').AsString+' '+LQuery.DataSet.FieldByName('NOME').AsString);
        UpdateParamValue(LCommand.Params,'COGNOME', LQuery.DataSet.FieldByName('COGNOME').AsString);
        UpdateParamValue(LCommand.Params,'NOME', LQuery.DataSet.FieldByName('NOME').AsString);
        UpdateParamValue(LCommand.Params,'CODFISCALE', LQuery.DataSet.FieldByName('CODFISC').AsString);
        UpdateParamValue(LCommand.Params,'INDIRIZZO', LQuery.DataSet.FieldByName('INDIRIZZO').AsString);
        UpdateParamValue(LCommand.Params,'CAP', LQuery.DataSet.FieldByName('CAP').AsString);
        UpdateParamValue(LCommand.Params,'PROVINCIAID', LQuery.DataSet.FieldByName('PROVINCIAID').AsString);
        UpdateParamValue(LCommand.Params,'IBAN', LQuery.DataSet.FieldByName('IBAN').AsString);
        UpdateParamValue(LCommand.Params,'EMAIL', LQuery.DataSet.FieldByName('EMAIL').AsString);
        UpdateParamValue(LCommand.Params,'INDIRIZZO_AMM', LQuery.DataSet.FieldByName('INDIRIZZO').AsString);
        UpdateParamValue(LCommand.Params,'CAP_AMM', LQuery.DataSet.FieldByName('CAP').AsString);
        UpdateParamValue(LCommand.Params,'COMUNE_AMMID', LQuery.DataSet.FieldByName('COMUNEID').AsString);
        UpdateParamValue(LCommand.Params,'PROVINCIA_AMMID', LQuery.DataSet.FieldByName('PROVINCIAID').AsString);
        UpdateParamValue(LCommand.Params,'COMUNEID', LQuery.DataSet.FieldByName('COMUNEID').AsString);
        UpdateParamValue(LCommand.Params,'FORMA_GIURIID', PRIVATE_INDIVIDUAL);
        UpdateParamValue(LCommand.Params,'FLAG_INDI_AMM', True);
        UpdateParamValue(LCommand.Params,'TELEFONO', LQuery.DataSet.FieldByName('TELEFONO').AsString);
        UpdateParamValue(LCommand.Params,'CELLULARE', LQuery.DataSet.FieldByName('CELLULARE').AsString);
        LCommand.Execute;
        Result := LCustomerId;
      end;
    finally
      LQuery.Close;
    end;
  finally
    FreeAndNil(LQuery);
    FreeAndNil(LCommand);
  end;


end;

//insert the collection entry for the subscription instalment
procedure InsertCollectionEntryFromPayments(const ARecord: TKRecord);
var
  LAutoReasonId: string;
  LAutoReasonDesc: string;
  LAutoAccountsQuery: TEFDBQuery;
  LReasonDataQuery: TEFDBQuery;
  LSubscriptionDataQuery: TEFDBQuery;
  LCommandInsertEntry: TEFDBCommand;
  LCommandInsertLine: TEFDBCommand;
  LEntryId : string;
  LLineId : string;
  LFinancialYearId : string;
  LNrMov : integer;
  LPayment: TKViewTableRecord;
  LEntryOk : boolean;
  LOpenItemId : string;
  LLineNumber : integer;
begin
  LEntryOk := False;
  LAutoAccountsQuery := TKConfig.Database.CreateDBQuery;
  LReasonDataQuery := TKConfig.Database.CreateDBQuery;
  LSubscriptionDataQuery := TKConfig.Database.CreateDBQuery;
  LCommandInsertEntry := TKConfig.Database.CreateDBCommand;
  LCommandInsertLine := TKConfig.Database.CreateDBCommand;
  try
    LSubscriptionDataQuery.CommandText := GetSQLSubscriptionData;
    LAutoReasonId := GetReason(PAYMENT_COLLECTION);
    LAutoReasonDesc := GetReasonDescription(PAYMENT_COLLECTION);
    if LAutoReasonId <> '' then
    begin
      LPayment := TKViewTableRecord(ARecord).Store.MasterRecord;
      LAutoAccountsQuery.CommandText := GetSQLAutomaticAccounts;
      LAutoAccountsQuery.Params.ParamByName('ID').AsString := PAYMENT_COLLECTION;
      LAutoAccountsQuery.Open;
      Try
        if not LAutoAccountsQuery.DataSet.IsEmpty then
        begin
          LCommandInsertEntry.CommandText := GetSQLInsertEntry;
          LCommandInsertLine.CommandText := GetSQLInsertLine;
          LSubscriptionDataQuery.CommandText := GetSQLSubscriptionData;
          LSubscriptionDataQuery.Params.ParamByName('ID').AsString := ARecord.FieldByName('SubscriptionInstalment_SubscriptionId').AsString;
          LSubscriptionDataQuery.Open;
          LReasonDataQuery.CommandText := GetSQLReasonData;
          LReasonDataQuery.Params.ParamByName('ID').AsString := LAutoReasonId;
          LReasonDataQuery.Open;
          LCommandInsertEntry.Connection.StartTransaction;
          Try
            //create the entry
            LEntryId := CreateCompactGuidStr;
            LFinancialYearId := GetFinancialYearFromDate(LPayment.FieldByName('PaymentDate').AsDateTime);
            LNrMov := NewEntryNumber(LFinancialYearId);
            UpdateParamValue(LCommandInsertEntry.Params,'ID', LEntryId);
            UpdateParamValue(LCommandInsertEntry.Params,'DX', LAutoReasonDesc);
            UpdateParamValue(LCommandInsertEntry.Params,'ESERCID', LFinancialYearId);
            UpdateParamValue(LCommandInsertEntry.Params,'NR_MOV', LNrMov);
            UpdateParamValue(LCommandInsertEntry.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
            UpdateParamValue(LCommandInsertEntry.Params,'DATA_REG', LPayment.FieldByName('PaymentDate').AsDateTime);
            UpdateParamValue(LCommandInsertEntry.Params,'TIPO_MOV', LReasonDataQuery.DataSet.FieldByName('TIPOREG').AsString);
            UpdateParamValue(LCommandInsertEntry.Params,'MOD_PAGAMENTOID', LPayment.FieldByName('PaymentMethodId').AsString);
            UpdateParamValue(LCommandInsertEntry.Params,'CAUSALEID', LAutoReasonId);
            UpdateParamValue(LCommandInsertEntry.Params,'IMPORTO', ARecord.FieldByName('PaidAmount').AsString);
            UpdateParamValue(LCommandInsertEntry.Params,'BANCAID', LPayment.FieldByName('DepositBankId').AsString);
            LCommandInsertEntry.Execute;
            LLineNumber := 0;
            while not LAutoAccountsQuery.DataSet.Eof do
            begin
              //for the debit line check against payment method and bank
              if LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString = DEBIT_SIGN then
              begin
                if (LPayment.FieldByName('DepositBankId').AsString <> LAutoAccountsQuery.DataSet.FieldByName('BANCAID').AsString) or
                   (LPayment.FieldByName('PaymentMethodId').AsString <> LAutoAccountsQuery.DataSet.FieldByName('MODPAGAMENTOID').AsString) then
                begin
                  LAutoAccountsQuery.DataSet.Next;
                  Continue;
                end
                else
                  LEntryOk := True;
              end;
              Inc(LLineNumber);

              //Create the entry lines
              LLineId := CreateCompactGuidStr;
              UpdateParamValue(LCommandInsertLine.Params,'ID', LLineId);
              UpdateParamValue(LCommandInsertLine.Params,'DX', ARecord.FieldByName('SubscriptionInstalment').AsString);
              UpdateParamValue(LCommandInsertLine.Params,'MOVIMENTOID', LEntryId);
              UpdateParamValue(LCommandInsertLine.Params,'NR_RIGA', LLineNumber);
              UpdateParamValue(LCommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
              UpdateParamValue(LCommandInsertLine.Params,'CONTOID', LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString);
              UpdateParamValue(LCommandInsertLine.Params,'DATASCADENZA', LPayment.FieldByName('PaymentDate').AsDateTime);

              //only the credit line carries the item reference
              if LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString = CREDIT_SIGN then
              begin
                LOpenItemId := LSubscriptionDataQuery.DataSet.FieldByName('CODFISC').AsString +' '+
                            DateToStr(ARecord.FieldByName('SubscriptionInstalment_DueDate').AsDateTime);

                UpdateParamValue(LCommandInsertLine.Params,'PARTITA', LOpenItemId);
              end
              else
                UpdateParamValue(LCommandInsertLine.Params,'PARTITA', '');

              UpdateParamValue(LCommandInsertLine.Params,'IMPORTO', ARecord.FieldByName('PaidAmount').AsString);
              UpdateParamValue(LCommandInsertLine.Params,'SEGNO', LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString);
              UpdateParamValue(LCommandInsertLine.Params,'NOMINATIVOID', LSubscriptionDataQuery.DataSet.FieldByName('NOMINATIVOID').AsString);
              UpdateParamValue(LCommandInsertLine.Params,'BANCAID', LPayment.FieldByName('DepositBankId').AsString);
              LCommandInsertLine.Execute;
              LAutoAccountsQuery.DataSet.Next;
            end;
            if not LEntryOk then
              Raise EKValidationError.Create(_('Debit account for the automatic collection reason not found!'));
            LCommandInsertEntry.Connection.CommitTransaction;
          Except
            LCommandInsertEntry.Connection.RollbackTransaction;
            raise;
          End;

        end;
      Finally
        LAutoAccountsQuery.Close;
      End;
    end;
  finally
    FreeAndNil(LAutoAccountsQuery);
    FreeAndNil(LReasonDataQuery);
    FreeAndNil(LSubscriptionDataQuery);
    FreeAndNil(LCommandInsertEntry);
    FreeAndNil(LCommandInsertLine);
  end;

end;

//insert the subscription entry
procedure InsertSubscriptionEntry(const ARecord: TKRecord);
var
  LAutoReasonId: string;
  LAutoReasonDesc: string;
  LAutoAccountsQuery: TEFDBQuery;
  LReasonDataQuery: TEFDBQuery;
  LCommandInsertEntry: TEFDBCommand;
  LCommandInsertLine: TEFDBCommand;
  LEntryId : string;
  LLineId : string;
  LFinancialYearId : string;
  LNrMov : integer;
  LSubscription: TKViewTableRecord;
  LInstalments: TKViewTableStore;
  LInstalment: TKViewTableRecord;
  LLineNumber : integer;
  LOpenItemId : string;
  I: Integer;
begin
  LAutoAccountsQuery := TKConfig.Database.CreateDBQuery;
  LReasonDataQuery := TKConfig.Database.CreateDBQuery;
  LCommandInsertEntry := TKConfig.Database.CreateDBCommand;
  LCommandInsertLine := TKConfig.Database.CreateDBCommand;
  try
    LAutoReasonId := GetReason(SUBSCRIPTION);
    LAutoReasonDesc := GetReasonDescription(SUBSCRIPTION);
    if LAutoReasonId <> '' then
    begin
      LAutoAccountsQuery.CommandText := GetSQLAutomaticAccounts;
      LAutoAccountsQuery.Params.ParamByName('ID').AsString := SUBSCRIPTION;
      LAutoAccountsQuery.Open;
      Try
        if not LAutoAccountsQuery.DataSet.IsEmpty then
        begin
          LCommandInsertEntry.CommandText := GetSQLInsertEntry;
          LCommandInsertLine.CommandText := GetSQLInsertLine;
          LReasonDataQuery.CommandText := GetSQLReasonData;
          LReasonDataQuery.Params.ParamByName('ID').AsString := LAutoReasonId;
          LReasonDataQuery.Open;
          LCommandInsertEntry.Connection.StartTransaction;
          Try
            //create the entry
            LEntryId := CreateCompactGuidStr;
            LFinancialYearId := GetFinancialYearFromDate(ARecord.FieldByName('SubscriptionDate').AsDateTime);
            LNrMov := NewEntryNumber(LFinancialYearId);
            UpdateParamValue(LCommandInsertEntry.Params,'ID', LEntryId);
            UpdateParamValue(LCommandInsertEntry.Params,'DX', LAutoReasonDesc);
            UpdateParamValue(LCommandInsertEntry.Params,'ESERCID', LFinancialYearId);
            UpdateParamValue(LCommandInsertEntry.Params,'NR_MOV', LNrMov);
            UpdateParamValue(LCommandInsertEntry.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
            UpdateParamValue(LCommandInsertEntry.Params,'DATA_REG', ARecord.FieldByName('SubscriptionDate').AsDateTime);
            UpdateParamValue(LCommandInsertEntry.Params,'TIPO_MOV', LReasonDataQuery.DataSet.FieldByName('TIPOREG').AsString);
            UpdateParamValue(LCommandInsertEntry.Params,'CAUSALEID', LAutoReasonId);
            UpdateParamValue(LCommandInsertEntry.Params,'IMPORTO', ARecord.FieldByName('SubscriptionTotal').AsString);
            LCommandInsertEntry.Execute;

            LSubscription := (ARecord as TKViewTableRecord);
            LSubscription.LoadDetailStores;
            LInstalments := LSubscription.GetDetailStoreByModelName('SubscriptionInstalment');
            LLineNumber := 0;
            while not LAutoAccountsQuery.DataSet.Eof do
            begin
              //create one debit line per instalment
              if LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString = DEBIT_SIGN then
              begin
                for I := 0 to LInstalments.RecordCount-1 do
                begin
                  LInstalment := LInstalments.Records[I];
                  LLineId := CreateCompactGuidStr;
                  Inc(LLineNumber);
                  UpdateParamValue(LCommandInsertLine.Params,'ID', LLineId);
                  UpdateParamValue(LCommandInsertLine.Params,'MOVIMENTOID', LEntryId);
                  UpdateParamValue(LCommandInsertLine.Params,'NR_RIGA', LLineNumber);
                  UpdateParamValue(LCommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
                  UpdateParamValue(LCommandInsertLine.Params,'CONTOID', LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString);
                  UpdateParamValue(LCommandInsertLine.Params,'SEGNO', LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString);
                  UpdateParamValue(LCommandInsertLine.Params,'DX', LInstalment.FieldByName('Description').AsString);
                  UpdateParamValue(LCommandInsertLine.Params,'DATASCADENZA', LInstalment.FieldByName('DueDate').AsDateTime);
                  LOpenItemId := LSubscription.FieldByName('TaxCode').AsString +' '+
                             DateToStr( LInstalment.FieldByName('DueDate').AsDateTime);
                  UpdateParamValue(LCommandInsertLine.Params,'PARTITA', LOpenItemId);
                  UpdateParamValue(LCommandInsertLine.Params,'IMPORTO', LInstalment.FieldByName('Amount').AsString);
                  UpdateParamValue(LCommandInsertLine.Params,'NOMINATIVOID', LInstalment.FieldByName('Subscription_PersonId').AsString);
                  LCommandInsertLine.Execute;
                end;
              end
              else //create the credit line with the subscription total
              begin
                LLineId := CreateCompactGuidStr;
                Inc(LLineNumber);
                UpdateParamValue(LCommandInsertLine.Params,'ID', LLineId);
                UpdateParamValue(LCommandInsertLine.Params,'MOVIMENTOID', LEntryId);
                UpdateParamValue(LCommandInsertLine.Params,'NR_RIGA', LLineNumber);
                UpdateParamValue(LCommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
                UpdateParamValue(LCommandInsertLine.Params,'CONTOID', LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString);
                UpdateParamValue(LCommandInsertLine.Params,'SEGNO', LAutoAccountsQuery.DataSet.FieldByName('SEGNO').AsString);
                UpdateParamValue(LCommandInsertLine.Params,'DX', ARecord.FieldByName('Description').AsString);
                UpdateParamValue(LCommandInsertLine.Params,'DATASCADENZA', ARecord.FieldByName('SubscriptionDate').AsDateTime);
                UpdateParamValue(LCommandInsertLine.Params,'PARTITA', '');
                UpdateParamValue(LCommandInsertLine.Params,'IMPORTO', ARecord.FieldByName('SubscriptionTotal').AsString);
                LCommandInsertLine.Execute;
              end;

              LAutoAccountsQuery.DataSet.Next;
            end;
            LCommandInsertEntry.Connection.CommitTransaction;
          Except
            LCommandInsertEntry.Connection.RollbackTransaction;
            raise;
          End;

        end;
      Finally
        LAutoAccountsQuery.Close;
      End;
    end;
  finally
    FreeAndNil(LAutoAccountsQuery);
    FreeAndNil(LReasonDataQuery);
    FreeAndNil(LCommandInsertEntry);
    FreeAndNil(LCommandInsertLine);
  end;
end;


//returns the automatic reason
function GetReason(const AAutomaticReasonId : string) : string;
begin
  Result := EFVarToStr(TKConfig.Database.GetSingletonValue('SELECT CAUSALEID FROM CAUSALI_AUTO WHERE ID = '+QuotedStr(AAutomaticReasonId)));
end;

//returns the automatic reason description
function GetReasonDescription(const AAutomaticReasonId : string) : string;
begin
  Result := EFVarToStr(TKConfig.Database.GetSingletonValue('SELECT DX FROM CAUSALI_AUTO WHERE ID = '+QuotedStr(AAutomaticReasonId)));
end;


function GetReasonPostingType(const AReasonId : string) : string;
begin
  Result := EFVarToStr(TKConfig.Database.GetSingletonValue('SELECT TIPOREG FROM CAUSALICONTABILI WHERE ID = '+QuotedStr(AReasonId)));
end;


//Returns the financial year open at the given date
function GetFinancialYearFromDate(const ADate : TDateTime): string;
begin
  Result := EFVarToStr(TKConfig.Database.GetSingletonValue('SELECT ID FROM ESERCIZICONTABILI WHERE DATAINIZIO <= '+QuotedStr(DateToCompactStr(ADate))+' AND DATAFINE >= '+QuotedStr(DateToCompactStr(ADate))+' AND STATO = ''A'' ' ));
end;

function GetSQLAutomaticAccounts: string;
begin
  Result := 'SELECT CA.SEGNO, CA.CONTOID, CA.MODPAGAMENTOID, '+
            'CA.BANCAID, C.DX DESC_CONTO, C.RIF_CLIENTE, '+
            'C.RIF_FORNITORE, C.RIF_CONTO_CORRENTE, C.RIF_SOCIO, '+
            'C.SEZIONE '+
            'FROM CONTI_AUTO CA LEFT OUTER JOIN CONTICONTABILI C ON C.ID = CA.CONTOID  WHERE CA.CAUSALEAUTOID = :ID ';
end;

function GetSQLReasonData: string;
begin
  Result := 'SELECT DX, TIPOREG, TIPOCAUSALE, RIFDTDOC, RIFNRDOC, RIFDTSCAD FROM CAUSALICONTABILI WHERE ID = :ID';
end;

//returns the query that inserts the entries
function GetSQLInsertEntry: string;
begin
  Result :=  'INSERT INTO MOVIMENTI_CONTABILI '+
             '(ID '+
             ',DX '+
             ',ESERCID '+
             ',NR_MOV '+
             ',UTENTE_INSERIMENTOID '+
             ',DATA_REG '+
             ',TIPO_MOV '+
             ',DATA_DOC '+
             ',NR_DOC '+
             ',MOD_PAGAMENTOID '+
             ',REG_IVAID '+
             ',NR_IVA '+
             ',CAUSALEID '+
             ',IMPORTO '+
             ',NOTE '+
             ',CLIENTEID '+
             ',FORNITOREID '+
             ',BANCAID ) '+
             'VALUES '+
             '(:ID '+
             ',:DX '+
             ',:ESERCID '+
             ',:NR_MOV '+
             ',:UTENTE_INSERIMENTOID '+
             ',:DATA_REG '+
             ',:TIPO_MOV '+
             ',:DATA_DOC '+
             ',:NR_DOC '+
             ',:MOD_PAGAMENTOID '+
             ',:REG_IVAID '+
             ',:NR_IVA '+
             ',:CAUSALEID '+
             ',:IMPORTO '+
             ',:NOTE '+
             ',:CLIENTEID '+
             ',:FORNITOREID '+
             ',:BANCAID ) ';
end;

//returns the query that inserts the lines
function GetSQLInsertLine: string;
begin
  Result :=  'INSERT INTO RIGHE_CONTABILI '+
             ' (ID '+
             ' ,DX '+
             ' ,MOVIMENTOID '+
             ' ,NR_RIGA '+
             ' ,UTENTE_INSERIMENTOID '+
             ' ,CONTOID '+
             ' ,DATASCADENZA '+
             ' ,PARTITA '+
             ' ,IMPORTO '+
             ' ,SEGNO '+
             ' ,COD_IVAID '+
             ' ,CENTRO_COSTOID '+
             ' ,CLIENTEID '+
             ' ,FORNITOREID '+
             ' ,BANCAID '+
             ' ,NOMINATIVOID) '+
             'VALUES '+
             ' (:ID '+
             ' ,:DX '+
             ' ,:MOVIMENTOID '+
             ' ,:NR_RIGA '+
             ' ,:UTENTE_INSERIMENTOID '+
             ' ,:CONTOID '+
             ' ,:DATASCADENZA '+
             ' ,:PARTITA '+
             ' ,:IMPORTO '+
             ' ,:SEGNO '+
             ' ,:COD_IVAID '+
             ' ,:CENTRO_COSTOID '+
             ' ,:CLIENTEID '+
             ' ,:FORNITOREID '+
             ' ,:BANCAID '+
             ' ,:NOMINATIVOID ) ';
end;

//returns the insert query for the VAT detail
function GetSQLInsertVatDetail: string;
begin
  Result := 'INSERT INTO DETTAGLI_IVA '+
            ' (ID '+
            ' ,DX '+
            ' ,MOVIMENTOID '+
            ' ,CODICE_IVAID '+
            ' ,IMPONIBILE '+
            ' ,IMPOSTA '+
            ' ,IMP_DETR '+
            ' ,IMP_INDETR) '+
            'VALUES '+
            ' (:ID '+
            ' ,:DX '+
            ' ,:MOVIMENTOID '+
            ' ,:CODICE_IVAID '+
            ' ,:IMPONIBILE '+
            ' ,:IMPOSTA '+
            ' ,:IMP_DETR '+
            ' ,:IMP_INDETR) ';
end;

//returns the insert query for the withholding taxes
function GetSQLInsertWithholdingDetail: string;
begin
  Result :=  'INSERT INTO DETTAGLI_RITENUTE '+
             ' (ID '+
             ' ,DX '+
             ' ,MOVIMENTOID '+
             ' ,DT_REG '+
             ' ,DT_COMP '+
             ' ,COD_TRIBUTO '+
             ' ,IMP_COMPENSO '+
             ' ,IMPONIBILE '+
             ' ,IMP_NON_SOGG_RA '+
             ' ,IMP_SOGG_RA '+
             ' ,DT_SCAD '+
             ' ,DT_VERS '+
             ' ,BANCA_VERSAMENTOID '+
             ' ,COD_ATT_INPS '+
             ' ,TIPO_RITENUTA '+
             ' ,MOD_LIQUIDAZIONEID '+
             ' ,STATUS '+
             ' ,FORNITOREID) '+
             'VALUES '+
             ' (:ID '+
             ' ,:DX '+
             ' ,:MOVIMENTOID '+
             ' ,:DT_REG '+
             ' ,:DT_COMP '+
             ' ,:COD_TRIBUTO '+
             ' ,:IMP_COMPENSO '+
             ' ,:IMPONIBILE '+
             ' ,:IMP_NON_SOGG_RA '+
             ' ,:IMP_SOGG_RA '+
             ' ,:DT_SCAD '+
             ' ,:DT_VERS '+
             ' ,:BANCA_VERSAMENTOID '+
             ' ,:COD_ATT_INPS '+
             ' ,:TIPO_RITENUTA '+
             ' ,:MOD_LIQUIDAZIONEID '+
             ' ,:STATUS '+
             ' ,:FORNITOREID) ';
end;

// returns the query that reads the subscription data
function GetSQLSubscriptionData: string;
begin
  Result := 'SELECT ' +
            '  NOMINATIVOID, '+
            '  CODFISC '+
            'FROM '+
            '  ISCRIZIONI '+
            'WHERE '+
            '  ID = :ID ';
end;


function GetSQLCounterpartBalance: string;
begin
  Result := 'SELECT ' +
            'ID,  '+
            'CODCONTO, ' +
            'DX,  ' +
	          'DX_CONTO, ' +
            'ESERCID, ' +
	          'NOMINATIVOID, ' +
            'CLIENTEID,  ' +
            'FORNITOREID, ' +
            'SEGNO_SALDO,  ' +
            'SALDO   ' +
            'FROM V_SALDOCONTI_DETT_BIL ' +
            'WHERE '+
            '  ID = :ID AND ESERCID = :ESERCID AND SALDO <> 0';
end;

procedure CloseAndReopenBalanceSheet(const ServerStore: TKViewTableStore);
var
  i : integer;
  LRecordStore : TKViewTableRecord;

  LOpeningAutoReasonId: string;
  LOpeningAutoReasonDesc: string;
  LOpeningReasonDataQuery: TEFDBQuery;
  LOpeningAutoAccountsQuery: TEFDBQuery;

  LClosingAutoReasonId: string;
  LClosingAutoReasonDesc: string;
  LClosingReasonDataQuery: TEFDBQuery;
  LClosingAutoAccountsQuery: TEFDBQuery;
  LCounterpartBalanceQuery: TEFDBQuery;

  LCommandInsertEntry: TEFDBCommand;
  LCommandInsertLine: TEFDBCommand;

  LClosingYearId, LOpeningYearId : string;
  LFinancialYearEnd : TDateTime;
  LFinancialYearStart : TDateTime;

  LProfitOrLoss : Currency;

  procedure GetYearEndData;
  var
    LNextYearQuery: TEFDBQuery;
    LFinancialYearId: TEFDBQuery;
  begin

    LClosingYearId := LRecordStore.FieldByName('FinancialYearId').AsString;

    //read the data of the selected financial year
    LFinancialYearId := TKConfig.Database.CreateDBQuery;
    try
      LFinancialYearId.CommandText := 'SELECT ID, DATAFINE, STATO FROM ESERCIZICONTABILI WHERE ID = :ID';
      LFinancialYearId.Params.ParamByName('ID').AsString := LClosingYearId;
      LFinancialYearId.Open;
      if (not LFinancialYearId.DataSet.IsEmpty) then
      begin
        if LFinancialYearId.DataSet.FieldByName('STATO').AsString = YEAR_CLOSED then
          raise EKValidationError.CreateWithAdditionalInfo(_('The financial year is already closed.'), _('Close/open financial year'));

        LFinancialYearEnd := LFinancialYearId.DataSet.FieldByName('DATAFINE').AsDateTime;
      end;
    finally
      LFinancialYearId.Free;
    end;

    LFinancialYearEnd := EFVarToDateTime(TKConfig.Database.GetSingletonValue('SELECT DATAFINE FROM ESERCIZICONTABILI WHERE ID = '+QuotedStr(LRecordStore.FieldByName('FinancialYearId').AsString))) ;

    LNextYearQuery := TKConfig.Database.CreateDBQuery;
    try
      LNextYearQuery.CommandText := 'SELECT ID, DATAINIZIO, STATO FROM ESERCIZICONTABILI WHERE DATAINIZIO = :DATAINI AND STATO = '+QuotedStr(YEAR_OPEN);
      LNextYearQuery.Params.ParamByName('DATAINI').AsDateTime := LFinancialYearEnd+1;
      LNextYearQuery.Open;
      if (not LNextYearQuery.DataSet.IsEmpty) then
      begin
        LOpeningYearId := LNextYearQuery.DataSet.FieldByName('ID').AsString;
        LFinancialYearStart := LNextYearQuery.DataSet.FieldByName('DATAINIZIO').AsDateTime;
      end
      else
        raise EKValidationError.CreateWithAdditionalInfo(_('The next open financial year was not found.'), _('Close/open financial year'));
    finally
      LNextYearQuery.Free;
    end;
  end;

begin
  LOpeningReasonDataQuery := TKConfig.Database.CreateDBQuery;
  LOpeningAutoAccountsQuery := TKConfig.Database.CreateDBQuery;

  LClosingReasonDataQuery := TKConfig.Database.CreateDBQuery;
  LClosingAutoAccountsQuery := TKConfig.Database.CreateDBQuery;

  LCounterpartBalanceQuery := TKConfig.Database.CreateDBQuery;

  LCommandInsertEntry := TKConfig.Database.CreateDBCommand;
  LCommandInsertLine := TKConfig.Database.CreateDBCommand;
  LClosingYearId := '';
  try
    //data of the opening reason
    LOpeningAutoReasonId := GetReason(BALANCE_SHEET_OPENING);
    LOpeningAutoReasonDesc := GetReasonDescription(BALANCE_SHEET_OPENING);

    //data of the closing reason
    LClosingAutoReasonId := GetReason(BALANCE_SHEET_CLOSING);
    LClosingAutoReasonDesc := GetReasonDescription(BALANCE_SHEET_CLOSING);

    if (LOpeningAutoReasonId <> '') and (LClosingAutoReasonId <> '') then
    begin
      //automatic accounts of the opening reason
      LOpeningAutoAccountsQuery.CommandText := GetSQLAutomaticAccounts;
      LOpeningAutoAccountsQuery.Params.ParamByName('ID').AsString := BALANCE_SHEET_OPENING;
      LOpeningAutoAccountsQuery.Open;

      //automatic accounts of the closing reason
      LClosingAutoAccountsQuery.CommandText := GetSQLAutomaticAccounts;
      LClosingAutoAccountsQuery.Params.ParamByName('ID').AsString := BALANCE_SHEET_CLOSING;
      LClosingAutoAccountsQuery.Open;


      LCounterpartBalanceQuery.CommandText := GetSQLCounterpartBalance;

      Try
        if (not LOpeningAutoAccountsQuery.DataSet.IsEmpty) and
           (not LClosingAutoAccountsQuery.DataSet.IsEmpty) then
        begin
          LCommandInsertEntry.CommandText := GetSQLInsertEntry;
          LCommandInsertLine.CommandText := GetSQLInsertLine;

          LOpeningReasonDataQuery.CommandText := GetSQLReasonData;
          LOpeningReasonDataQuery.Params.ParamByName('ID').AsString := LOpeningAutoReasonId;
          LOpeningReasonDataQuery.Open;

          LClosingReasonDataQuery.CommandText := GetSQLReasonData;
          LClosingReasonDataQuery.Params.ParamByName('ID').AsString := LClosingAutoReasonId;
          LClosingReasonDataQuery.Open;

          LCommandInsertEntry.Connection.StartTransaction;
          Try
            //create the entries
            LProfitOrLoss := 0;

            for i := 0 to ServerStore.RecordCount-1 do
            begin
              LRecordStore := ServerStore.Records[i];

              //read the financial year data
              if (LClosingYearId = '') then
                GetYearEndData;

              if (LRecordStore.FieldByName('Level').AsString = 'S') and
                 (LRecordStore.FieldByName('Balance').AsCurrency <> 0) then
              begin
                //Compute the profit and loss of the year
                if (LRecordStore.FieldByName('Section').AsString = 'R') or
                   (LRecordStore.FieldByName('Section').AsString = 'C') then
                begin
                  if LRecordStore.FieldByName('Sign').AsString = DEBIT_SIGN then
                    LProfitOrLoss := LProfitOrLoss+LRecordStore.FieldByName('Balance').AsCurrency
                  else
                    LProfitOrLoss := LProfitOrLoss-LRecordStore.FieldByName('Balance').AsCurrency;
                end;

                if LCounterpartBalanceQuery.DataSet.Active then
                  LCounterpartBalanceQuery.Close;

                //read the counterpart detail of the account
                LCounterpartBalanceQuery.Params.ParamByName('ID').AsString := LRecordStore.FieldByName('AccountId').AsString;
                LCounterpartBalanceQuery.Params.ParamByName('ESERCID').AsString := LClosingYearId;
                LCounterpartBalanceQuery.Open;

                //TODO: one closing and one opening entry is created per sub-account
                //they could be grouped by parent code, one entry per account
                //closing entry of the financial year
                InsertClosingEntry(LCommandInsertEntry, LCommandInsertLine, LClosingYearId,
                               LClosingAutoReasonId, LClosingAutoReasonDesc, LFinancialYearEnd,
                               LClosingReasonDataQuery, LClosingAutoAccountsQuery,
                               LCounterpartBalanceQuery,
                               LRecordStore.FieldByName('AccountId').AsString,
                               LRecordStore.FieldByName('Description').AsString,
                               LRecordStore.FieldByName('Sign').AsString,
                               LRecordStore.FieldByName('Section').AsString,
                               LRecordStore.FieldByName('Balance').AsCurrency);

                //opening entry of the next year for the balance sheet
                if (LRecordStore.FieldByName('Section').AsString = 'A') or
                   (LRecordStore.FieldByName('Section').AsString = 'P')  then
                  InsertOpeningEntry(LCommandInsertEntry, LCommandInsertLine, LOpeningYearId,
                                 LOpeningAutoReasonId, LOpeningAutoReasonDesc, LFinancialYearStart,
                                 LOpeningReasonDataQuery, LOpeningAutoAccountsQuery,
                                 LCounterpartBalanceQuery,
                                 LRecordStore.FieldByName('AccountId').AsString,
                                 LRecordStore.FieldByName('Description').AsString,
                                 LRecordStore.FieldByName('Sign').AsString,
                                 LRecordStore.FieldByName('Balance').AsCurrency);
              end;
            end;

            if LProfitOrLoss <> 0 then
            begin
              //result of the year, closing side
              InsertProfitOrLossEntry(LCommandInsertEntry, LCommandInsertLine, LClosingYearId,
                                 LClosingAutoReasonId, LClosingAutoReasonDesc, LFinancialYearEnd,
                                 LClosingReasonDataQuery, LClosingAutoAccountsQuery,
                                 LProfitOrLoss, False);

              //result of the year, opening side
              InsertProfitOrLossEntry(LCommandInsertEntry, LCommandInsertLine, LOpeningYearId,
                                 LOpeningAutoReasonId, LOpeningAutoReasonDesc, LFinancialYearStart,
                                 LOpeningReasonDataQuery, LOpeningAutoAccountsQuery,
                                 LProfitOrLoss, True);

            end;


            CloseFinancialYear(LClosingYearId);
            LCommandInsertEntry.Connection.CommitTransaction;
          Except
            LCommandInsertEntry.Connection.RollbackTransaction;
            raise;

          End;

        end;
      Finally
        LOpeningAutoAccountsQuery.Close;
        LClosingAutoAccountsQuery.Close;
        if LCounterpartBalanceQuery.DataSet.Active then
          LCounterpartBalanceQuery.Close;
      End;
    end;


  finally
    FreeAndNil(LOpeningAutoAccountsQuery);
    FreeAndNil(LOpeningReasonDataQuery);
    FreeAndNil(LClosingAutoAccountsQuery);
    FreeAndNil(LClosingReasonDataQuery);
    FreeAndNil(LCounterpartBalanceQuery);
    FreeAndNil(LCommandInsertEntry);
    FreeAndNil(LCommandInsertLine);
  end;

end;


procedure InsertProfitOrLossEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AFinancialYearId, AAutoReasonId, AAutoReasonDesc : string; ADate : TDateTime;
  AReasonDataQuery, AAutoAccountsQuery: TEFDBQuery;
  LProfitOrLoss : Currency; ANewFinancialYear : boolean);
var
  LDebitAccount, LCreditAccount : string;
  LDebitDesc, LCreditDesc : string;
  LEntryId : string;
  LLineId : string;
  LNrMov : integer;
  LLineNumber : integer;

  LAutomaticReasonId : string;
  LAutoReasonId, LAutoReasonDesc : string;
  LAutoAccountsQuery: TEFDBQuery;
  LReasonDataQuery: TEFDBQuery;


  LAccountId, LDescription, LSign, LSection : string;

begin
  //insert the entry that posts the result of the year
  if ANewFinancialYear then
  begin
    if LProfitOrLoss > 0 then
      LAutomaticReasonId := PREV_YEAR_PROFIT
    else
      LAutomaticReasonId := PREV_YEAR_LOSS;
  end
  else
  begin
    if LProfitOrLoss > 0 then
      LAutomaticReasonId := YEAR_PROFIT
    else
      LAutomaticReasonId := YEAR_LOSS;
  end;

  LReasonDataQuery := TKConfig.Database.CreateDBQuery;
  LAutoAccountsQuery := TKConfig.Database.CreateDBQuery;
  try

    LAutoReasonId := GetReason(LAutomaticReasonId);
    LAutoReasonDesc := GetReasonDescription(LAutomaticReasonId);
    if LAutoReasonId <> '' then
    begin
      LAutoAccountsQuery.CommandText := GetSQLAutomaticAccounts;
      LAutoAccountsQuery.Params.ParamByName('ID').AsString := LAutomaticReasonId;
      LAutoAccountsQuery.Open;
      Try

        LReasonDataQuery.CommandText := GetSQLReasonData;
        LReasonDataQuery.Params.ParamByName('ID').AsString := LAutoReasonId;
        LReasonDataQuery.Open;

        LEntryId := CreateCompactGuidStr;
        LNrMov := NewEntryNumber(AFinancialYearId);
        UpdateParamValue(ACommandInsertEntry.Params,'ID', LEntryId);
        UpdateParamValue(ACommandInsertEntry.Params,'DX', LAutoReasonDesc);
        UpdateParamValue(ACommandInsertEntry.Params,'ESERCID', AFinancialYearId);
        UpdateParamValue(ACommandInsertEntry.Params,'NR_MOV', LNrMov);
        UpdateParamValue(ACommandInsertEntry.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
        UpdateParamValue(ACommandInsertEntry.Params,'DATA_REG', ADate);
        UpdateParamValue(ACommandInsertEntry.Params,'TIPO_MOV', LReasonDataQuery.DataSet.FieldByName('TIPOREG').AsString);
        UpdateParamValue(ACommandInsertEntry.Params,'CAUSALEID', LAutoReasonId);
        UpdateParamValue(ACommandInsertEntry.Params,'IMPORTO', Abs(LProfitOrLoss));
        ACommandInsertEntry.Execute;

        if LAutoAccountsQuery.DataSet.Locate('SEGNO', CREDIT_SIGN, []) then
        begin
          LCreditAccount := LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
          LCreditDesc  := LAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;

          if (ANewFinancialYear and (LProfitOrLoss > 0)) or
             ((not ANewFinancialYear) and (LProfitOrLoss < 0))  then
          begin
            LAccountId := LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
            LDescription := LAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
            //ON A NEW FINANCIAL YEAR THE SIGN TO PASS IS DEBIT
            if ANewFinancialYear then
              LSign := DEBIT_SIGN
            else
              LSign := CREDIT_SIGN;
            LSection := LAutoAccountsQuery.DataSet.FieldByName('SEZIONE').AsString;

          end;

        end
        else
          raise EKValidationError.CreateWithAdditionalInfo(_('Credit account not found.'), _('Posting of profit/loss for the year'));


        if LAutoAccountsQuery.DataSet.Locate('SEGNO', DEBIT_SIGN, []) then
        begin
          LDebitAccount := LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
          LDebitDesc :=  LAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;

          if (ANewFinancialYear and (LProfitOrLoss < 0)) or
             ((not ANewFinancialYear) and (LProfitOrLoss > 0))  then
          begin
            LAccountId := LAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
            LDescription := LAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
            //ON A NEW FINANCIAL YEAR THE SIGN TO PASS IS CREDIT
            if ANewFinancialYear then
              LSign := CREDIT_SIGN
            else
              LSign := DEBIT_SIGN;
            LSection := LAutoAccountsQuery.DataSet.FieldByName('SEZIONE').AsString;

          end;
        end
        else
          raise EKValidationError.CreateWithAdditionalInfo(_('Debit account not found.'), _('Posting of profit/loss for the year'));

        LLineNumber := 0;
        //insert debit line
        LLineId := CreateCompactGuidStr;
        Inc(LLineNumber);
        UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
        UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
        UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
        UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
        UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LDebitAccount);
        UpdateParamValue(ACommandInsertLine.Params,'SEGNO', DEBIT_SIGN);
        UpdateParamValue(ACommandInsertLine.Params,'DX', LDebitDesc);
        UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', ADate);
        UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
        UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LProfitOrLoss));
        UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
        UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
        UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
        ACommandInsertLine.Execute;

        //insert credit line
        LLineId := CreateCompactGuidStr;
        Inc(LLineNumber);
        UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
        UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
        UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
        UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
        UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LCreditAccount);
        UpdateParamValue(ACommandInsertLine.Params,'SEGNO', CREDIT_SIGN);
        UpdateParamValue(ACommandInsertLine.Params,'DX', LCreditDesc);
        UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', ADate);
        UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
        UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LProfitOrLoss));
        UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
        UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
        UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
        ACommandInsertLine.Execute;

        if ANewFinancialYear then
        begin
          InsertOpeningEntry(ACommandInsertEntry, ACommandInsertLine, AFinancialYearId,
                         AAutoReasonId, AAutoReasonDesc, ADate,
                         AReasonDataQuery, AAutoAccountsQuery,
                         nil,
                         LAccountId,
                         LDescription,
                         LSign,
                         Abs(LProfitOrLoss));
        end
        else
        begin
          //closing entry of the financial year
          InsertClosingEntry(ACommandInsertEntry, ACommandInsertLine, AFinancialYearId,
                         AAutoReasonId, AAutoReasonDesc, ADate,
                         AReasonDataQuery, AAutoAccountsQuery,
                         nil,
                         LAccountId,
                         LDescription,
                         LSign,
                         LSection,
                         Abs(LProfitOrLoss));
        end;


      Finally
        LAutoAccountsQuery.Close;
      End;
    end;
  finally
    LReasonDataQuery.Free;
    LAutoAccountsQuery.Free;
  end;
end;

procedure InsertClosingEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AClosingYearId, AClosingAutoReasonId, AClosingAutoReasonDesc : string; AFinancialYearEnd : TDateTime;
  AClosingReasonDataQuery, AClosingAutoAccountsQuery, ACounterpartBalanceQuery: TEFDBQuery;
  AAccountId, ADescription, ASign, ASection : string; ABalance : Currency);
var
  LEntryId : string;
  LLineId : string;
  LNrMov : integer;
  LLineNumber : integer;
  LTotalDebit : Currency;
  LTotalCredit : Currency;

  procedure InsertBalanceLines(AAccountBalance : Currency; ABalanceSign: string;
                             APersonId : string = ''; ASupplierId : string = ''; ACustomerId : string = '');
  var
    LSign : string;
  begin

    if ABalanceSign = DEBIT_SIGN then
      LSign := CREDIT_SIGN
    else
      LSign := DEBIT_SIGN;


    if LSign = DEBIT_SIGN then
      LTotalDebit := LTotalDebit + AAccountBalance
    else
      LTotalCredit := LTotalCredit + AAccountBalance;

    //insert debit line
    LLineId := CreateCompactGuidStr;
    Inc(LLineNumber);
    UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
    UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
    UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
    UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
    UpdateParamValue(ACommandInsertLine.Params,'CONTOID', AAccountId);
    UpdateParamValue(ACommandInsertLine.Params,'SEGNO', LSign);
    UpdateParamValue(ACommandInsertLine.Params,'DX', ADescription);
    UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearEnd);
    UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
    UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', AAccountBalance);
    UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', APersonId);
    UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', ASupplierId);
    UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', ACustomerId);
    ACommandInsertLine.Execute;

  end;

  procedure InsertBalanceSheetLines;
  var
    LAccount : string;
    LDesc : string;
    LSection : string;
  begin

    if (ASection = 'A') or
       (ASection = 'P') then
      LSection := 'P'
    else
      LSection := 'C';

    //BALANCE SHEET DEBIT LINE
    if LTotalCredit > 0 then
    begin

      if AClosingAutoAccountsQuery.DataSet.Locate('SEGNO;SEZIONE', VarArrayOf([DEBIT_SIGN,LSection]), []) then
      begin
        LAccount := AClosingAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
        LDesc :=  AClosingAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
      end;

      LLineId := CreateCompactGuidStr;
      Inc(LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
      UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
      UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
      UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LAccount);
      UpdateParamValue(ACommandInsertLine.Params,'SEGNO', DEBIT_SIGN);
      UpdateParamValue(ACommandInsertLine.Params,'DX', LDesc);
      UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearEnd);
      UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
      UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LTotalCredit));
      UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
      UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
      UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
      ACommandInsertLine.Execute;
    end;

    //BALANCE SHEET CREDIT LINE
    if LTotalDebit > 0 then
    begin
      if AClosingAutoAccountsQuery.DataSet.Locate('SEGNO;SEZIONE', VarArrayOf([CREDIT_SIGN,LSection]), []) then
      begin
        LAccount := AClosingAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
        LDesc :=  AClosingAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
      end;
      //insert credit line
      LLineId := CreateCompactGuidStr;
      Inc(LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
      UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
      UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
      UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LAccount);
      UpdateParamValue(ACommandInsertLine.Params,'SEGNO', CREDIT_SIGN);
      UpdateParamValue(ACommandInsertLine.Params,'DX', LDesc);
      UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearEnd);
      UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
      UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LTotalDebit));
      UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
      UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
      UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
      ACommandInsertLine.Execute;
    end;
  end;

begin
  LLineNumber := 0;
  LTotalCredit := 0;
  LTotalDebit := 0;

  //insert the closing entry
  LEntryId := CreateCompactGuidStr;
  LNrMov := NewEntryNumber(AClosingYearId);
  UpdateParamValue(ACommandInsertEntry.Params,'ID', LEntryId);
  UpdateParamValue(ACommandInsertEntry.Params,'DX', AClosingAutoReasonDesc);
  UpdateParamValue(ACommandInsertEntry.Params,'ESERCID', AClosingYearId);
  UpdateParamValue(ACommandInsertEntry.Params,'NR_MOV', LNrMov);
  UpdateParamValue(ACommandInsertEntry.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
  UpdateParamValue(ACommandInsertEntry.Params,'DATA_REG', AFinancialYearEnd);
  UpdateParamValue(ACommandInsertEntry.Params,'TIPO_MOV', AClosingReasonDataQuery.DataSet.FieldByName('TIPOREG').AsString);
  UpdateParamValue(ACommandInsertEntry.Params,'CAUSALEID', AClosingAutoReasonId);
  UpdateParamValue(ACommandInsertEntry.Params,'IMPORTO', Abs(ABalance));
  ACommandInsertEntry.Execute;

  //create the lines with the counterpart detail
  if Assigned(ACounterpartBalanceQuery) and  (not ACounterpartBalanceQuery.DataSet.IsEmpty) then
  begin
    with ACounterpartBalanceQuery.DataSet do
    begin
      First;
      while not Eof do
      begin
        InsertBalanceLines(Abs(FieldByName('SALDO').AsCurrency),
                         FieldByName('SEGNO_SALDO').AsString,
                         FieldByName('NOMINATIVOID').AsString,
                         FieldByName('FORNITOREID').AsString,
                         FieldByName('CLIENTEID').AsString );
        Next;
      end;
    end;
  end
  else
  begin
    InsertBalanceLines(ABalance, ASign);
  end;

  InsertBalanceSheetLines;

  //update the entry amount
  TKConfig.Database.ExecuteImmediate('UPDATE MOVIMENTI_CONTABILI SET IMPORTO = '+StringReplace(CurrToStr(LTotalCredit+LTotalDebit), ',', '.',[])+' WHERE ID = '+QuotedStr(LEntryId) );

end;

procedure InsertOpeningEntry(const ACommandInsertEntry, ACommandInsertLine: TEFDBCommand;
  AOpeningYearId, AOpeningAutoReasonId, AOpeningAutoReasonDesc : string; AFinancialYearStart : TDateTime;
  AOpeningReasonDataQuery, AOpeningAutoAccountsQuery, ACounterpartBalanceQuery: TEFDBQuery;
  AAccountId, ADescription, ASign : string; ABalance : Currency);
var
  LEntryId : string;
  LLineId : string;
  LNrMov : integer;
  LLineNumber : integer;
  LTotalDebit : Currency;
  LTotalCredit : Currency;

  procedure InsertBalanceLines(AAccountBalance : Currency; ABalanceSign : string;
                             APersonId : string = ''; ASupplierId : string = '';
                             ACustomerId : string = '');
  begin


    if ABalanceSign = DEBIT_SIGN then
      LTotalDebit := LTotalDebit + AAccountBalance
    else
      LTotalCredit := LTotalCredit + AAccountBalance;

    //insert debit line
    LLineId := CreateCompactGuidStr;
    Inc(LLineNumber);
    UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
    UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
    UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
    UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
    UpdateParamValue(ACommandInsertLine.Params,'CONTOID', AAccountId);
    UpdateParamValue(ACommandInsertLine.Params,'SEGNO', ASign);
    UpdateParamValue(ACommandInsertLine.Params,'DX', ADescription);
    UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearStart);
    UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
    UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', AAccountBalance);
    UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', APersonId);
    UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', ASupplierId);
    UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', ACustomerId);
    ACommandInsertLine.Execute;

  end;

  procedure InsertBalanceSheetLines;
  var
    LAccount : string;
    LDesc : string;
  begin


    //BALANCE SHEET DEBIT LINE
    if LTotalCredit > 0 then
    begin

      if AOpeningAutoAccountsQuery.DataSet.Locate('SEGNO', DEBIT_SIGN, []) then
      begin
        LAccount := AOpeningAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
        LDesc :=  AOpeningAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
      end;

      LLineId := CreateCompactGuidStr;
      Inc(LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
      UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
      UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
      UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LAccount);
      UpdateParamValue(ACommandInsertLine.Params,'SEGNO', DEBIT_SIGN);
      UpdateParamValue(ACommandInsertLine.Params,'DX', LDesc);
      UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearStart);
      UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
      UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LTotalCredit));
      UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
      UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
      UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
      ACommandInsertLine.Execute;
    end;

    //BALANCE SHEET CREDIT LINE
    if LTotalDebit > 0 then
    begin
      if AOpeningAutoAccountsQuery.DataSet.Locate('SEGNO', CREDIT_SIGN, []) then
      begin
        LAccount := AOpeningAutoAccountsQuery.DataSet.FieldByName('CONTOID').AsString;
        LDesc :=  AOpeningAutoAccountsQuery.DataSet.FieldByName('DESC_CONTO').AsString;
      end;
      //insert credit line
      LLineId := CreateCompactGuidStr;
      Inc(LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'ID', LLineId);
      UpdateParamValue(ACommandInsertLine.Params,'MOVIMENTOID', LEntryId);
      UpdateParamValue(ACommandInsertLine.Params,'NR_RIGA', LLineNumber);
      UpdateParamValue(ACommandInsertLine.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
      UpdateParamValue(ACommandInsertLine.Params,'CONTOID', LAccount);
      UpdateParamValue(ACommandInsertLine.Params,'SEGNO', CREDIT_SIGN);
      UpdateParamValue(ACommandInsertLine.Params,'DX', LDesc);
      UpdateParamValue(ACommandInsertLine.Params,'DATASCADENZA', AFinancialYearStart);
      UpdateParamValue(ACommandInsertLine.Params,'PARTITA', '');
      UpdateParamValue(ACommandInsertLine.Params,'IMPORTO', Abs(LTotalDebit));
      UpdateParamValue(ACommandInsertLine.Params,'NOMINATIVOID', '');
      UpdateParamValue(ACommandInsertLine.Params,'FORNITOREID', '');
      UpdateParamValue(ACommandInsertLine.Params,'CLIENTEID', '');
      ACommandInsertLine.Execute;
    end;
  end;

begin
  LTotalCredit := 0;
  LTotalDebit := 0;
  LLineNumber := 0;

  //insert the opening entry
  LEntryId := CreateCompactGuidStr;
  LNrMov := NewEntryNumber(AOpeningYearId);
  UpdateParamValue(ACommandInsertEntry.Params,'ID', LEntryId);
  UpdateParamValue(ACommandInsertEntry.Params,'DX', AOpeningAutoReasonDesc);
  UpdateParamValue(ACommandInsertEntry.Params,'ESERCID', AOpeningYearId);
  UpdateParamValue(ACommandInsertEntry.Params,'NR_MOV', LNrMov);
  UpdateParamValue(ACommandInsertEntry.Params,'UTENTE_INSERIMENTOID', TKConfig.Instance.Authenticator.UserName);
  UpdateParamValue(ACommandInsertEntry.Params,'DATA_REG', AFinancialYearStart);
  UpdateParamValue(ACommandInsertEntry.Params,'TIPO_MOV', AOpeningReasonDataQuery.DataSet.FieldByName('TIPOREG').AsString);
  UpdateParamValue(ACommandInsertEntry.Params,'CAUSALEID', AOpeningAutoReasonId);
  UpdateParamValue(ACommandInsertEntry.Params,'IMPORTO', Abs(ABalance));
  ACommandInsertEntry.Execute;
  //create the accounting lines
  if Assigned(ACounterpartBalanceQuery) and  (not ACounterpartBalanceQuery.DataSet.IsEmpty) then
  begin
    with ACounterpartBalanceQuery.DataSet do
    begin
      First;
      while not Eof do
      begin
        InsertBalanceLines(Abs(FieldByName('SALDO').AsCurrency),
                         FieldByName('SEGNO_SALDO').AsString,
                         FieldByName('NOMINATIVOID').AsString,
                         FieldByName('FORNITOREID').AsString,
                         FieldByName('CLIENTEID').AsString );
        Next;
      end;
    end;
  end
  else
  begin
    InsertBalanceLines(ABalance, ASign);
  end;

  InsertBalanceSheetLines;

  //update the entry amount
  TKConfig.Database.ExecuteImmediate('UPDATE MOVIMENTI_CONTABILI SET IMPORTO = '+StringReplace(CurrToStr(LTotalCredit+LTotalDebit), ',', '.',[])+' WHERE ID = '+QuotedStr(LEntryId) );

end;
procedure CloseFinancialYear(AFinancialYearId : string);
begin
  TKConfig.Database.ExecuteImmediate('UPDATE ESERCIZICONTABILI SET STATO = '+QuotedStr(YEAR_CLOSED)+' WHERE ID = '+QuotedStr(AFinancialYearId) );
end;

end.
