{-------------------------------------------------------------------------------
   Copyright 2012-2026 Ethea S.r.l.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------}

/// <summary>
///  Standard WebModule for KittoX WebBroker deployments (ISAPI/Apache). Adding
///  this unit to an empty WebBroker project routes every request to the shared
///  TKWebBrokerHandler, with no application-specific code required.
/// </summary>
unit Kitto.WebBroker.WebModule;

{$I Kitto.Defines.inc}

interface

uses
  System.SysUtils,
  System.Classes,
  Web.HTTPApp;

type
  /// <summary>
  ///  Standard WebModule that triggers the KittoX engine. Just add this unit
  ///  to an empty Webbroker project (and remove the one generated by the wizard)
  ///  and it will hook into the system through the WebModuleClass global variable.
  /// </summary>
  TKWebModule = class(TWebModule)
    /// <summary>Default action: delegates every request to TKWebBrokerHandler.Current.</summary>
    procedure WebModule1DefaultHandlerAction(Sender: TObject;
      Request: TWebRequest; Response: TWebResponse; var Handled: Boolean);
  end;

var
  /// <summary>WebBroker entry point: the component class the framework instantiates
  /// as the web module (set to TKWebModule).</summary>
  WebModuleClass: TComponentClass = TKWebModule;

implementation

uses
  Kitto.WebBroker.Handler;

{%CLASSGROUP 'System.Classes.TPersistent'}

{$R *.dfm}

{ TKWebModule }

procedure TKWebModule.WebModule1DefaultHandlerAction(Sender: TObject;
  Request: TWebRequest; Response: TWebResponse; var Handled: Boolean);
begin
  Handled := TKWebBrokerHandler.Current.HandleRequest(Request, Response);
end;

end.
